using System;

namespace SignalRouter.Protocol
{
    // A recording handle is the recording file's stem, generated by the
    // runtime: "rec-<utcstamp>-<8 lowercase-hex chars>". It carries no path
    // separators, dots, or uppercase, so it cannot express directory traversal
    // and needs no host-side handle→path map — the runtime resolves it to
    // "<artifactRoot>/<handle>.jsonl" by construction (ADR 0007, item 8d). The
    // no-map property is what lets a handle survive a domain reload. Path
    // confinement still runs at the recorder as defense in depth (§19).
    public static class RecordingHandles
    {
        public const string Prefix = "rec-";

        public const int MaxHandleChars = 64;

        public static bool IsValid(string? handle)
        {
            if (handle == null
                || handle.Length < Prefix.Length + 1
                || handle.Length > MaxHandleChars
                || !handle.StartsWith(Prefix, StringComparison.Ordinal))
            {
                return false;
            }

            for (var index = 0; index < handle.Length; index++)
            {
                var character = handle[index];
                var isLower = character >= 'a' && character <= 'z';
                var isDigit = character >= '0' && character <= '9';
                if (!isLower && !isDigit && character != '-')
                {
                    return false;
                }
            }

            return true;
        }

        public static void Require(string handle, string parameterName)
        {
            if (!IsValid(handle))
            {
                throw new ArgumentException(
                    "A recording handle must be a lowercase, separator-free stem "
                    + "beginning with 'rec-'.",
                    parameterName);
            }
        }
    }
}
